# Generated by Django 3.0.6 on 2020-06-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200618_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dislokes',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
